### ISSUE TITLE
hzToMels / melsToHz coefficient

### ISSUE THREAD

**Issue by nicolaspanel** [joshjung/node-mfcc#3]
Hi,

First, thank you for sharing this project.

I am a little bit confused with the implementation of the [hzToMels](https://github.com/vail-systems/node-mfcc/blob/master/src/mfcc.js#L157) method. Why are you using `1127` instead of `2595`?

BR

**Comment by joshjung** [comment]
@nicolaspanel It has been over a year since I wrote this code but I believe we are using the 1127 because `Math.log` is the natural logarithm, and not base 10. See here:

https://en.wikipedia.org/wiki/Mel_scale

2595 for log base 10
1127 for log base e

Hope that helps!

**Comment by nicolaspanel** [comment]
tx!
